In [30]:
#import the pandas library to read a CSV file
import pandas as pd
#import the numpy library to create a numpy array
import numpy as np

In [31]:
data = pd.read_csv('C:/Users/pc/Downloads/diabetes_prediction_dataset.csv')

In [32]:
data

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [33]:
data['gender'] = data['gender'].map({'Male': 1, 'Female': 0})

In [34]:
# Check for NaN (Not a Number) values in your DataFrame
data.isnull().sum()

gender                 18
age                     0
hypertension            0
heart_disease           0
smoking_history         0
bmi                     0
HbA1c_level             0
blood_glucose_level     0
diabetes                0
dtype: int64

In [35]:
# Handle NaN values (Drop rows with NaN)
data.dropna(inplace=True)

In [36]:
data

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0.0,80.0,0,1,never,25.19,6.6,140,0
1,0.0,54.0,0,0,No Info,27.32,6.6,80,0
2,1.0,28.0,0,0,never,27.32,5.7,158,0
3,0.0,36.0,0,0,current,23.45,5.0,155,0
4,1.0,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,0.0,80.0,0,0,No Info,27.32,6.2,90,0
99996,0.0,2.0,0,0,No Info,17.37,6.5,100,0
99997,1.0,66.0,0,0,former,27.83,5.7,155,0
99998,0.0,24.0,0,0,never,35.42,4.0,100,0
99999,0.0,57.0,0,0,current,22.43,6.6,90,0

In [37]:
data.drop(['smoking_history','HbA1c_level'], axis =1, inplace=True)

In [38]:
data.to_csv('df_diabetes.csv', index=False)

In [39]:
data

,gender,age,hypertension,heart_disease,bmi,blood_glucose_level,diabetes
0,0.0,80.0,0,1,25.19,140,0
1,0.0,54.0,0,0,27.32,80,0
2,1.0,28.0,0,0,27.32,158,0
3,0.0,36.0,0,0,23.45,155,0
4,1.0,76.0,1,1,20.14,155,0
...,...,...,...,...,...,...,...
99995,0.0,80.0,0,0,27.32,90,0
99996,0.0,2.0,0,0,17.37,100,0
99997,1.0,66.0,0,0,27.83,155,0
99998,0.0,24.0,0,0,35.42,100,0
99999,0.0,57.0,0,0,22.43,90,0

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99982 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               99982 non-null  float64
 1   age                  99982 non-null  float64
 2   hypertension         99982 non-null  int64
 3   heart_disease        99982 non-null  int64
 4   bmi                  99982 non-null  float64
 5   blood_glucose_level  99982 non-null  int64
 6   diabetes             99982 non-null  int64
dtypes: float64(3), int64(4)
memory usage: 6.1 MB

In [41]:
data.describe()

,gender,age,hypertension,heart_disease,bmi,blood_glucose_level,diabetes
count,99982.000000,99982.000000,99982.000000,99982.000000,99982.000000,99982.000000,99982.000000
mean,0.414375,41.888076,0.074863,0.039427,27.320757,138.057810,0.085015
std,0.492616,22.517206,0.263172,0.194610,6.636853,40.709469,0.278906
min,0.000000,0.080000,0.000000,0.000000,10.010000,80.000000,0.000000
25%,0.000000,24.000000,0.000000,0.000000,23.630000,100.000000,0.000000
50%,0.000000,43.000000,0.000000,0.000000,27.320000,140.000000,0.000000
75%,1.000000,60.000000,0.000000,0.000000,29.580000,159.000000,0.000000
max,1.000000,80.000000,1.000000,1.000000,95.690000,300.000000,1.000000

In [42]:
#create two variables, X (features) and y (target)
X = data[['gender', 'age','hypertension','heart_disease','diabetes','bmi']]
y = data['blood_glucose_level']

In [43]:
from sklearn.datasets import make_regression

In [44]:
#split your data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [45]:
#create a linear regression model using the LinearRegression class
from sklearn.linear_model import LinearRegression
model=LinearRegression()
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
model2=GradientBoostingRegressor()
model3=RandomForestRegressor()

In [46]:
#train your linear regression model on your training data
model.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

RandomForestRegressor()

In [47]:
#make predictions on your test data
y_pred = model.predict(X_test)
y_pred2 = model2.predict(X_test)
y_pred3 = model3.predict(X_test)

In [48]:
#compare these predictions (y_pred) to the actual values (y_test)
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")
print(f"R-squared: {r2}")

Mean Squared Error: 1354.9702172809325
Root Mean Squared Error: 36.8099200933788
R-squared: 0.18604987414203333

In [49]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred2)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred2)

print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")
print(f"R-squared: {r2}")

Mean Squared Error: 1357.1363044978987
Root Mean Squared Error: 36.83933094530761
R-squared: 0.18474867435152642

In [50]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred3)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred3)

print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")
print(f"R-squared: {r2}")

Mean Squared Error: 1634.7063691031658
Root Mean Squared Error: 40.43150218707148
R-squared: 0.018008338557844228

In [51]:
new_data = {
    'gender': 0.0,
    'age': 57.0,
    'hypertension': 0,
    'heart_disease': 0,
    'diabetes': 0,
    'bmi': 24.18,
    
}

# Creating a DataFrame from the new data (assuming you have pandas imported as pd)
new_df = pd.DataFrame([new_data])

# Making predictions using the pre-trained model
predicted_value = model.predict(new_df)

print(f"Predicted value: {predicted_value[0]}")

Predicted value: 132.78432064714892

In [52]:
new_data = {
    'gender': 0.0,
    'age': 57.0,
    'hypertension': 0,
    'heart_disease': 0,
    'diabetes': 0,
    'bmi': 24.18,
    
}

# Creating a DataFrame from the new data (assuming you have pandas imported as pd)
new_df = pd.DataFrame([new_data])

# Making predictions using the pre-trained model
predicted_value = model2.predict(new_df)

print(f"Predicted value: {predicted_value[0]}")

Predicted value: 131.86129591386367

In [53]:
new_data = {
    'gender': 0.0,
    'age': 57.0,
    'hypertension': 0,
    'heart_disease': 0,
    'diabetes': 0,
    'bmi': 24.18,
    
}

# Creating a DataFrame from the new data (assuming you have pandas imported as pd)
new_df = pd.DataFrame([new_data])

# Making predictions using the pre-trained model
predicted_value = model3.predict(new_df)

print(f"Predicted value: {predicted_value[0]}")

Predicted value: 130.12083333333334

In [54]:
#actual value = 130

In [55]:
import pickle
import skl2onnx
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

In [56]:
with open("diabete.pickle","wb") as f : 
  pickle.dump(model3,f)

In [57]:
with open("diabete.pickle","rb") as f : 
  model = pickle.load(f)

In [58]:
# Convertir en ONNX
#initial_type = [("float_input", FloatTensorType([None, X.shape[1]]))]
#onnx_model = convert_sklearn(model3, initial_types=initial_type)

# Sauvegarder en ONNX
#with open("model.onnx", "wb") as f:
    #f.write(onnx_model.SerializeToString())